FROM metacell/jupyter-neuron:development

ARG netpyneuiBranch=feature-osb_deployment

RUN echo $netpyneuiBranch

# Clone NetPyNE-UI and install the development version
RUN git clone -b $netpyneuiBranch https://github.com/rodriguez-facundo/NetPyNE-UI &&\
  cd NetPyNE-UI/utilities &&\
  python install.py branch $netpyneuiBranch

WORKDIR $HOME
RUN git clone --depth 1 https://github.com/Neurosim-lab/netpyne_workspace
WORKDIR $HOME/netpyne_workspace
RUN ln -sfn $HOME/NetPyNE-UI/netpyne_ui/tests tests

CMD jupyter notebook --debug --NotebookApp.default_url=/geppetto --NotebookApp.token='' --library=netpyne_ui